services:
  lucnv-chat-app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: unless-stopped
    ports:
      - "9009:9000"
    volumes:
      - .:/var/www
      - ./docker/php/supervisord.d/queue-worker.conf:/etc/supervisor/conf.d/queue-worker.conf
      - ./docker/php/supervisord.d/schedule.conf:/etc/supervisor/conf.d/schedule.conf
      - ./docker/php/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf

    depends_on:
      - lucnv-chat-db
      - lucnv-chat-redis
    networks:
      - lucnv-chat-network

  #Database
  lucnv-chat-db:
    image: mysql:8.0
    restart: always
    volumes:
      - db-store:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3310:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Lucnv@12
      MYSQL_DATABASE: lucnv_chat
    networks:
      - lucnv-chat-network

  #Nginx
  lucnv-chat-nginx:
    image: nginx:alpine
    ports:
      - "8089:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs:/var/log/nginx
      - ./src:/var/www
      - ./:/work/lucnv-chat:delegated
    depends_on:
      - lucnv-chat-app
    networks:
      - lucnv-chat-network

  #Redis
  lucnv-chat-redis:
    image: redis:alpine
    volumes:
      - redis-store:/data
    ports:
      - "6379:6379"
    networks:
      - lucnv-chat-network

  #mailhog
  mailhog:
    image: mailhog/mailhog
    container_name: laravel-mailhog
    ports:
      - "8029:8025"
    networks:
      - lucnv-chat-network

volumes:
  db-store:
  redis-store:

networks:
    lucnv-chat-network:
        driver: bridge
